sudo: required
services:
  - docker

before_install:
  - docker build -t xciber/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run xciber/react-test yarn test -- --coverage

after_success:
  - docker build -t xciber/multi-client ./client
  - docker build -t xciber/multi-server ./server
  - docker build -t xciber/multi-worker ./worker
  - docker build -t xciber/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  - docker push xciber/multi-client
  - docker push xciber/multi-server
  - docker push xciber/multi-worker
  - docker push xciber/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-162641069043"
  bucker_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"